test: Update OIDC integration test
stackabletech/druid-operator pull request #565
Opened 2024-05-10 09:47 UTC by labrenbe

# Description

Update the OIDC integration test to do a full OIDC login flow and check that data ingestion is not broken.

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-05-22 12:21 UTC, adwk67 requested changes
OIDC test runs on Kind and Openshift with the suggested change.

2024-05-27 08:48 UTC, labrenbe commented on tests/templates/kuttl/oidc/51-install-test-container.yaml.j2
> +{% if test_scenario['values']['oidc-use-tls'] == 'true' %}
I've updated the PR with your proposed change

2024-05-27 11:55 UTC, adwk67 commented on tests/templates/kuttl/oidc/51-install-test-container.yaml.j2
> +{% if test_scenario['values']['oidc-use-tls'] == 'true' %}
Thanks!

2024-05-27 14:44 UTC, adwk67 approved these changes

2024-05-27 14:47 UTC, merged

2024-05-28 07:11 UTC, sbernauer commented
@labrenbe the nightly tests are failing wuth `KeyError: 'DRUID_OIDC'`, do you mind having a look?
https://ci.stackable.tech/view/01%20Operator%20Tests%20(nightly)/job/druid-operator-it-nightly/520/