chore: promote Druid 30.0.0 to LTS, deprecate 26.0.0, remove 28.0.1
stackabletech/druid-operator pull request #631
Opened 2024-09-27 08:26 UTC by NickLarsenNZ

# Description

Part of https://github.com/stackabletech/docker-images/issues/833

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [x] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-09-27 11:34 UTC, sbernauer requested changes

2024-09-27 11:34 UTC, sbernauer commented on CHANGELOG.md
> +- Promote Druid `30.0.0` to LTS, deprecate `28.0.1` ([#631]).
```suggestion
- Promote Druid `30.0.0` to LTS, deprecate `26.0.0` ([#631]).
```

2024-09-28 07:06 UTC, NickLarsenNZ commented on CHANGELOG.md
> +- Promote Druid `30.0.0` to LTS, deprecate `28.0.1` ([#631]).
Good catch

2024-09-30 06:21 UTC, sbernauer approved these changes

2024-09-30 06:23 UTC, merged