feat: `requestedSecretLifetime` role group property added
stackabletech/druid-operator pull request #660
Opened 2024-11-28 12:01 UTC by razvan

# Description

Depends on: https://github.com/stackabletech/operator-rs/pull/915

Part of: https://github.com/stackabletech/issues/issues/586

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-11-29 08:00 UTC, sbernauer commented
Just for the record: I reviews https://github.com/stackabletech/hbase-operator/pull/598, the comments also apply here

2024-12-02 10:30 UTC, sbernauer commented
Just for the record for others: I'd say https://github.com/stackabletech/hbase-operator/pull/598 is the template - which is currently under review. Please place your feedback there

2024-12-04 09:14 UTC, sbernauer requested changes
Only nits

2024-12-04 09:14 UTC, sbernauer commented on CHANGELOG.md
> +- The lifetime of auto generated TLS certificates is now configurable with the role and roleGroup config property `requestedSecretLifetime` ([#660])
```suggestion
- The lifetime of auto generated TLS certificates is now configurable with the role and roleGroup
  config property `requestedSecretLifetime`. This helps reducing frequent Pod restarts ([#660]).
```

2024-12-04 09:14 UTC, sbernauer commented on rust/crd/src/lib.rs
>      pub graceful_shutdown_timeout: Option<Duration>,
```suggestion
    pub graceful_shutdown_timeout: Option<Duration>,

```

2024-12-04 09:14 UTC, sbernauer commented on rust/crd/src/lib.rs
>      pub graceful_shutdown_timeout: Option<Duration>,
```suggestion
    pub graceful_shutdown_timeout: Option<Duration>,

```

2024-12-04 09:14 UTC, sbernauer commented on rust/crd/src/lib.rs
>      pub graceful_shutdown_timeout: Option<Duration>,
```suggestion
    pub graceful_shutdown_timeout: Option<Duration>,

```

2024-12-04 09:14 UTC, sbernauer commented on rust/crd/src/lib.rs
>      pub graceful_shutdown_timeout: Option<Duration>,
```suggestion
    pub graceful_shutdown_timeout: Option<Duration>,

```

2024-12-04 09:14 UTC, sbernauer commented on rust/crd/src/lib.rs
>      pub graceful_shutdown_timeout: Option<Duration>,
```suggestion
    pub graceful_shutdown_timeout: Option<Duration>,

```

2024-12-04 09:14 UTC, sbernauer commented on rust/crd/src/security.rs
> +        requested_secret_lifetime: Duration,
In all the other operators you passed it by reference ;) (remember to deref it in line 207)
```suggestion
        requested_secret_lifetime: &Duration,
```

2024-12-04 09:14 UTC, sbernauer commented on rust/operator-binary/src/druid_controller.rs
> +            merged_rolegroup_config.requested_secret_lifetime,
```suggestion
            &merged_rolegroup_config.requested_secret_lifetime,
```

2024-12-04 09:14 UTC, sbernauer commented on rust/crd/src/security.rs
> +                            .with_auto_tls_cert_lifetime(requested_secret_lifetime)
```suggestion
                            .with_auto_tls_cert_lifetime(*requested_secret_lifetime)
```

2024-12-04 09:33 UTC, sbernauer approved these changes
Thanks! Let's hope it compiles ^^

2024-12-04 10:00 UTC, merged

2024-12-05 21:20 UTC, lfrancke commented
Will this be in 24.11.1? It's a new feature so I guess it shouldn't but I'm not sure if we're set up with release branches?