Remove Ports from Role CRD
stackabletech/druid-operator pull request #76
Opened 2021-12-22 15:35 UTC by fhennig

## Description

Without the agent, ports don't need to be configurable anymore

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

2021-12-22 16:08 UTC, maltesander requested changes
Just one unwrap comment and the zookeeper references in the custom resource examples go for "simple" zk cluster. In the zookeeper example its called "simple-zk".

2021-12-22 16:08 UTC, maltesander commented on rust/operator-binary/src/config.rs
> +    format!("{}{}{}{}", ports, common, role_specifics, others.unwrap())
Go for Result and "?" here instead of unwrap?

2021-12-23 09:41 UTC, maltesander approved these changes
LGTM.

2021-12-23 09:41 UTC, fhennig commented
bors merge

2021-12-23 09:48 UTC, merged